name: Deploy Flask App to EKS
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::173003893026:role/OIDC-github-actions
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to ECR
      run: |
        IMAGE_TAG=latest
        docker build -t ${{ steps.login-ecr.outputs.registry }}/flask-app:$IMAGE_TAG .
        docker push ${{ steps.login-ecr.outputs.registry }}/flask-app:$IMAGE_TAG
        
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name dev-eks
    
    - name: Verify Cluster Access
      run: |
        kubectl get nodes






        
